secrets:
  db_secrets:
    file: ./secrets/db_secrets

services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_secrets
    secrets:
      - db_secrets
    volumes:
      - pg_data:/var/lib/postgresql/data
      - secrets:/run/secrets
    networks:
      - app_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    container_name: studytrack-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_PORT: ${APP_PORT}
      JAVA_OPTS: ${JAVA_OPTS}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JDBC_DRIVER: ${JDBC_DRIVER}
      JPA_DDL_AUTO: ${JPA_DDL_AUTO}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL}
    secrets:
      - db_secrets
    networks:
      - app_net
    ports:
      - "${APP_PORT}:8080"
networks:
  app_net:
    driver: bridge
volumes:
  pg_data:
  secrets:
