apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: studytrack-app
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Executa depois do job de migration
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: studytrack-app
  template:
    metadata:
      labels:
        app: studytrack-app
    spec:
      containers:
        - name: studytrack-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: APP_PORT
              value: "{{ .Values.app.port }}"
            - name: JAVA_OPTS
              value: "{{ .Values.env.JAVA_OPTS }}"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
          ports:
            - containerPort: {{ .Values.app.port }}
  strategy:
    {{- if eq .Values.strategy "blueGreen"}}
    blueGreen:
      activeService: studytrack-app-service
      {{- if eq .Values.environment "dev"}}
      previewService: studytrack-app-preview
      {{- end}}
      autoPromotionEnabled: false
    {{- else if eq .Values.strategy "canary"}}
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 130}
        - setWeight: 50
        - pause: {duration: 10}
      maxSurge: 1
      maxUnavailable: 0
      stableService: studytrack-app-service
    {{- end}}