apiVersion: v1
kind: Service
metadata:
  name: studytrack-app-preview
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.previewPort }}
      targetPort: {{ .Values.app.previewPort }}
      nodePort: {{ .Values.service.previewNodePort | default 30081 }}
  selector:
    app: studytrack-app