apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.postgres.user }}
  password: {{ .Values.postgres.password }}