apiVersion: v1
kind: Service
metadata:
  name: studytrack-app-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      {{- end }}
  selector:
    app: studytrack-app