# dev values
namespace: studytrack-dev
image:
  repository: ghcr.io/estherdefreitas/studytrack-devops
  tag: "007c69d"

app:
  port: 8080
  replicas: 2

postgres:
  image: postgres:16-alpine
  host: studytrack-db-rw
  port: 5432
  db: studytrack-db-rw
  user: devuser
  password: devpassword
  pvcSize: 100Mi

service:
  type: NodePort
  nodePort: 30080

env:
  JAVA_OPTS: ""
  SPRING_PROFILES_ACTIVE: dev