# prod values
namespace: studytrack-prod
image:
  repository: ghcr.io/estherdefreitas/studytrack-devops
  tag: "af4ad4a"

app:
  port: 8080
  previewPort: 8083
  replicas: 2

postgres:
  image: postgres:16-alpine
  host: studytrack-db-rw
  port: 5432
  db: studytrack-db-rw
  user: produser
  password: prodpassword
  pvcSize: 1Gi

service:
  type: NodePort
  nodePort: 30082

env:
  JAVA_OPTS: "-Xms512m -Xmx1024m"
  SPRING_PROFILES_ACTIVE: prod

strategy: canary
environment: prod