name: Build and Push image

on:
  push:
    branches: [main]
    paths-ignore:
      - 'helm/values-*.yaml'  # Evita loop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short commit SHA
        id: vars
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.short_sha }} -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.short_sha }}
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Update Helm values with new image tag
        run: |
          sed -i "s/^\(\s*tag:\s*\).*/\1${{ steps.vars.outputs.short_sha }}/" helm/values-dev.yaml
          sed -i "s/^\(\s*tag:\s*\).*/\1${{ steps.vars.outputs.short_sha }}/" helm/values-prod.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add helm/values-dev.yaml
          git add helm/values-prod.yaml
          git commit -m "ci: update image tag to ${{ steps.vars.outputs.short_sha }} [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"